### ISSUE TITLE
makecourse fails in some scenarios when using Python 3.9

### ISSUE THREAD

**Issue by dualspiral** [coursebuilder-ncl/makecourse#74]
makecourse commit: c4f9626724708a62c84e7779ceb09dfa00b4ffad (but it looks like it'll be present in the newer commits)

When compiling a course using Python 3.9+, the following error is somtimes given:

```
  File "/Users/drnaylor/opt/anaconda3/envs/makecourse39/lib/python3.9/site-packages/makeCourse/markdownRenderer/image_processor/imgproc.py", line 20, in run
    images = root.getiterator("img")
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

[Full stacktrace here](https://gist.github.com/dualspiral/f216f20db2593869b8b9e32ee56aeb2b#file-makecourse-build-error).

This is because [`xml.etree.ElementTree.Element.getiterator` was deprecated in Python 3.2 and removed in 3.9](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getiterator). The docs suggest using [`iter` instead](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.iter).

**Steps to Reproduce**

* Install `makecourse` into a new venv or conda environment that targets Python 3.9
* Clone the sample course into a new directory
* Run `make`

Alternatively, use an existing course and run `make clean` on it first.

---

Note that the workaround is to set the environment that makecourse is installed in to use Python 3.8 (or earlier) - so this isn't blocking me!

**Comment by georgestagg** [comment]
Thanks, a lot! I made a simple replacement from `getiterator` to `iter` and it seems to work!

**Comment by prowlett** [comment]
I'm getting this error with a Markdown file. I believe this is because you still have a `getiterator` in `makeCourse/markdownRenderer/markdown_figure/mdfigure.py`. 

I updated `makecourse` to 5056f0b. I haven't used it possibly since before Easter. Certainly I've updated Ubuntu (and now have Python 3.9) since then. Anyway, I can reproduce the error just by creating a Markdown file:

```
# Test page

Hello.
```

When I run `makecourse` I get this:

```
Running makecourse for directory /home/.../coursebuilder/to-break
Traceback (most recent call last):
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 386, in <module>
    main()
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 374, in main
    mc.build_with_theme(theme)
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 330, in build_with_theme
    self.process()
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 242, in process
    processor.visit(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 126, in visit
    super().visit(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 30, in visit
    return fn(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 44, in visit_part
    self.visit(subitem)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 126, in visit
    super().visit(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 30, in visit
    return fn(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 134, in visit_chapter
    self.makePDF(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 157, in makePDF
    asyncio.get_event_loop().run_until_complete(self.renderer.to_pdf(item))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/render.py", line 74, in to_pdf
    self.render_item(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/render.py", line 58, in render_item
    html = self.to_html(item, template_file)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/render.py", line 69, in to_html
    return template.render(context)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/chapter.html", line 2, in top-level template code
    {% import "macros.html" as macros %}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/item.html", line 2, in top-level template code
    {% import "macros.html" as macros %}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/base.html", line 50, in top-level template code
    {% block main %}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/chapter.html", line 54, in block "main"
    {{item.as_html()|safe}}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/item.py", line 153, in as_html
    html = self.markdownRenderer.render(self, outPath)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/markdownRenderer/__init__.py", line 43, in render
    content = markdown(content_item.markdown_content(), extensions=mdx_extensions, extension_configs=self.extension_configs)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/markdown/core.py", line 391, in markdown
    return md.convert(text)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/markdown/core.py", line 272, in convert
    newRoot = treeprocessor.run(root)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/markdownRenderer/markdown_figure/mdfigure.py", line 24, in run
    images = root.getiterator("img")
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```
