### ISSUE TITLE
texmf error - makecourse won't run after update to 379205d

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#81]
I just updated to 379205d and re-ran makecourse on the last version to run successfully. It crashed quickly with the following error message I don't understand. Any ideas? Using Ubuntu with TeX Live 2020.

```
Running makecourse for directory /home/...
Traceback (most recent call last):
  File "/home/.../coursebuilder_env/bin/makecourse", line 393, in <module>
    main()
  File "/home/.../coursebuilder_env/bin/makecourse", line 381, in main
    mc.build_with_theme(theme)
  File "/home/.../coursebuilder_env/bin/makecourse", line 337, in build_with_theme
    self.process()
  File "/home/.../coursebuilder_env/bin/makecourse", line 249, in process
    processor.visit(item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 126, in visit
    super().visit(item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 30, in visit
    return fn(item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 44, in visit_part
    self.visit(subitem)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 126, in visit
    super().visit(item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 30, in visit
    return fn(item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 134, in visit_chapter
    self.makePDF(item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/process.py", line 155, in makePDF
    latex.runPdflatex(self.course, item)
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/latex.py", line 69, in runPdflatex
    if item.recently_built():
  File "/home/.../coursebuilder_env/lib/python3.8/site-packages/makeCourse/item.py", line 77, in recently_built
    if input_file.stat().st_mtime > self.last_built and input_file.suffix not in extensions:
  File "/usr/lib/python3.8/pathlib.py", line 1197, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/texmf/web2c/texmf.cnf'
```

**Comment by georgestagg** [comment]
Does 1e69abc help? I think TeXLive might have updated and a file that used to exist no longer does. So, when `makecourse` is checking prerequisite files listed in pdflatex's `.fls` files (to see if they're newer and if a rebuild is necessary) it falls over because it can't find the age of a non-existent file. I've made a small change to simply rebuild the file in such cases.

**Comment by prowlett** [comment]
Yes that works now, thanks! It took 9 minutes to re-run, so I guess it rebuilt everything, but after this, new changes compile quickly again.
