### ISSUE TITLE
xml.etree.ElementTree getchildren removed in Python 3.9

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#92]
Similar to #74, I run `makecourse` on a file and get the error:

```
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

I see in [the xml.etree.ElementTree documentation](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren) that `getchildren` is 

> Deprecated since version 3.2, will be removed in version 3.9: Use list(elem) or iteration.

I also notice `getchildren()` and `getiterator()` are the only two on that page that mention Python 3.9, but I see the [release notes for Python 3.9](https://docs.python.org/3.9/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code) say this, which I don't 100% understand or know how to apply here but hopefully you do:

> Test your application with the -W default command-line option to see DeprecationWarning and PendingDeprecationWarning, or even with -W error to treat them as errors. Warnings Filter can be used to ignore warnings from third-party code.

Here's the full error:

```
Traceback (most recent call last):
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 386, in <module>
    main()
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 374, in main
    mc.build_with_theme(theme)
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 330, in build_with_theme
    self.process()
  File "/home/.../coursebuilder/coursebuilder_env/bin/makecourse", line 242, in process
    processor.visit(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 126, in visit
    super().visit(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 30, in visit
    return fn(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 44, in visit_part
    self.visit(subitem)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 126, in visit
    super().visit(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 30, in visit
    return fn(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 134, in visit_chapter
    self.makePDF(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/process.py", line 157, in makePDF
    asyncio.get_event_loop().run_until_complete(self.renderer.to_pdf(item))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/render.py", line 74, in to_pdf
    self.render_item(item)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/render.py", line 58, in render_item
    html = self.to_html(item, template_file)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/render.py", line 69, in to_html
    return template.render(context)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/chapter.html", line 2, in top-level template code
    {% import "macros.html" as macros %}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/item.html", line 2, in top-level template code
    {% import "macros.html" as macros %}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/base.html", line 50, in top-level template code
    {% block main %}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/themes/default/templates/chapter.html", line 54, in block "main"
    {{item.as_html()|safe}}
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/item.py", line 153, in as_html
    html = self.markdownRenderer.render(self, outPath)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/makeCourse/markdownRenderer/__init__.py", line 43, in render
    content = markdown(content_item.markdown_content(), extensions=mdx_extensions, extension_configs=self.extension_configs)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/markdown/core.py", line 391, in markdown
    return md.convert(text)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/markdown/core.py", line 272, in convert
    newRoot = treeprocessor.run(root)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/mdx_outline.py", line 206, in run
    self.process_nodes(root)
  File "/home/.../coursebuilder/coursebuilder_env/lib/python3.9/site-packages/mdx_outline.py", line 154, in process_nodes
    for child in node.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by georgestagg** [comment]
It looks like this is coming from an external package, `mdx_outline`. The package hasn't been updated since 2017, so there's a chance it's no longer maintained. I've included a copy of it in the latest `makecourse` commit, patched to remove the `getchildren` function and to use `list(elem)` instead. Hopefully that helps.

I've also submitted a pull request at https://github.com/aleray/mdx_outline/pull/5. If accepted, we can switch back to using an unmodified version of the package.
